### ISSUE TITLE
Error message upon attempt to validate packard.tei.xml using XMLTools plugin for Notepad++

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#6]
I normally validate OSIS XML files using the **XMLTools** plugin for **Notepad++**

Trrying this with `packard.tei.xml` gave a critical error. See [screenshot](https://www.dropbox.com/s/37sorjj5mp5swmp/Screenshot%202021-03-01%2021.22.56.png?dl=0).

There must be something seriously amiss with one of these lines:
```
 <TEI xmlns="http://www.crosswire.org/2013/TEIOSIS/namespace"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.crosswire.org/2013/TEIOSIS/namespace
                          http://www.crosswire.org/OSIS/teiP5osis.2.5.0.xsd">
```
What does **DTD is prohibited** actually mean?

**Comment by pierre-amadio** [comment]
I used the line coming from the crosswire wiki:
https://wiki.crosswire.org/TEI_Dictionaries

xmllint does not complain (well, it makes warning about ignoring the inline schema as it is specified as an argument, but it validates)

[melmoth@pamadio packard]$ xmllint --noout --schema teiP5osis.2.5.0.xsd  packard.tei.xml 
http://www.crosswire.org/OSIS/dcr.xsd:3: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'http://www.crosswire.org/OSIS/teiP5osis.2.5.0.xsd' for the namespace 'http://www.crosswire.org/2013/TEIOSIS/namespace', since this namespace was already imported with the schema located at 'teiP5osis.2.5.0.xsd'.
http://www.crosswire.org/OSIS/examples.xsd:4: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Skipping import of schema located at 'http://www.crosswire.org/OSIS/teiP5osis.2.5.0.xsd' for the namespace 'http://www.crosswire.org/2013/TEIOSIS/namespace', since this namespace was already imported with the schema located at 'teiP5osis.2.5.0.xsd'.
packard.tei.xml validates

It looks to me this is probably a xmltools plugins issue such as

https://community.notepad-plus-plus.org/topic/19447/xml-tools-validation-problem-with-inline-dtd/2

**Comment by DavidHaslam** [comment]
Thanks for well researched response.
